name: build-linux
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Linux desktop deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter build linux --release

      - name: Tar bundle
        run: |
          cd build/linux/x64/release/bundle
          tar czf ../../../nokz-linux.tar.gz *

      - uses: actions/upload-artifact@v4
        with:
          name: nokz-linux
          path: build/linux/x64/release/nokz-linux.tar.gz
