name: macOS build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter 3.24.x
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.3'
          cache: true

      - run: flutter --version
      - run: flutter pub get

      - name: Ensure CocoaPods
        run: |
          sudo gem install cocoapods -N || true
          pod repo update || true

      - run: flutter config --enable-macos-desktop
      - run: flutter build macos --release

      - name: Package app as zip
        run: |
          cd build/macos/Build/Products/Release
          ditto -c -k --sequesterRsrc --keepParent vpn_client.app ../../../../../nokz-macos.zip

      - uses: actions/upload-artifact@v4
        with:
          name: nokz-macos
          path: nokz-macos.zip
